name: Build and Push Docker Image 
on:
  push:
    branches:
      - main  # 或你希望触发构建的分支
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # 登录到 GitHub Container Registry
          username: ${{ github.actor }}  # 使用 GitHub 当前的用户名（由 GitHub Actions 自动获取）
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token

      # Step 4: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nf/koyeb-nginx-grpc:latest .

      # Step 5: 推送 Docker 镜像
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nf/koyeb-nginx-grpc:latest
